# Generated by Django 5.2.7 on 2025-10-27 16:02

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(choices=[(1, 'نوبت واریزی 1'), (2, 'نوبت واریزی 2'), (3, 'نوبت واریزی 3'), (4, 'نوبت واریزی 4'), (5, 'نوبت واریزی 5'), (6, 'نوبت واریزی 6'), (7, 'نوبت واریزی 7'), (8, 'نوبت واریزی 8'), (9, 'نوبت واریزی 9'), (10, 'نوبت واریزی 10')], verbose_name='نوبت واریز')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ واریزی')),
                ('payment_date', django_jalali.db.models.jDateField(verbose_name='تاریخ واریز (شمسی)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'واریز',
                'verbose_name_plural': 'واریزی\u200cها',
                'ordering': ['installment_number', 'payment_date'],
            },
        ),
    ]
