# Generated by Django 5.2.7 on 2025-10-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedPaymentDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveSmallIntegerField(unique=True)),
                ('due_date', models.DateField()),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
    ]
