# Generated by Django 5.2.7 on 2025-11-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_payment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید اعلامی تعاونی'),
        ),
    ]
